### PR TITLE
DRAFT Convention over configuration for formatter files

### PR DESCRIPTION
**Pull request by markiewb**
Hi Vojtech @krasa ,
please have a look at my draft for the issue #181 

Configuration files .settings/org.eclipse.jdt.core.prefs, mechanic-formatter.epf, .settings/mechanic-formatter.epf are supported.

If the configuration file is not found in the current directory of the file to format, then the search continues one directory above until the module root is reached (you won't search for configuration files at / :D).

OPEN
* Unitests (I could not get it run the existing tests JavaCodeFormatterFacadeTest based on the master 65507b890543ef6cc4cc94297ab1997e8c91a000 using
IntelliJ IDEA 2019.3 EAP (Ultimate Edition) Build #IU-193.4778.7, built on October 23, 2019 - StackoverflowError) - Which configuration do you use/recommend?
* the convention name for the *.epf: formatter.epf or java-formatter.epf as proposals
* update the readme
* checkbox in the options to disable the search by convention approach (which will be enabled by default)

What do you think?

### CODE REVIEW

**Comment by krasa** [comment]
You would need a completely different test, like this: https://github.com/krasa/EclipseCodeFormatter/commit/27c7f90bd7c2f0d22a12fff6e1720cab4ab9c2a

Looks fine to me (and it should also disable the config file input validation).

**Comment by markiewb** [comment]
@krasa: I improved the PR based on your commit. 

* Support of hierarchical projects like Maven-Multimodules (parent projects must be loaded in IDEA else the parent module is not found)
* Make the implementation testable (using static TESTING-approach - i forgot the name of the pattern - I read about this in "Refactoring Legacy Code" https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052)
* No options yet :( No time yet

BTW you have disabled code in postProcess by accident? https://github.com/krasa/EclipseCodeFormatter/commit/27c7f90bd7c2f0d22a12fff6e1720cab4ab9c2a

**Comment by krasa** [comment]
> BTW you have disabled code in postProcess by accident? 27c7f90

Intentional, it did not work in that test and all post processors ware deleted anyway... I did not test it much, so not sure if it will not break something.

**Comment by krasa** [comment]
Merged manually. Seems good to go.

**Comment by markiewb** [comment]
Cool. I already forgot that pull request.

**Comment by FichteFoll** [comment]
Are there any conventions for the xml file that I could use?

**Comment by krasa** [comment]
No. 
Following files are searched for: ".settings/org.eclipse.jdt.core.prefs", ".settings/mechanic-formatter.epf", "mechanic-formatter.epf".

**Comment by FichteFoll** [comment]
Would it make sense to add one? Currently I have my formatting options just in a `format.xml` file in the project root due to a lack of a better name, but I suppose there are no conventions that could be applied here.

**Comment by krasa** [comment]
Why not,  `eclipse-code-formatter.xml` seems to be used often.

**Comment by krasa** [comment]
Resolving of import order should be also added...

**Pull request closed without merging**
